import Image from "next/image";
import type { ReactNode } from "react";
import type { Pending as PendingValue } from "@/content/shared";
import { PersonCard } from "./person-card";

/** Page gutter + max width, shared by every band so the margins line up. */
export function Container({
  children,
  className = "",
}: {
  children: ReactNode;
  className?: string;
}) {
  return (
    <div className={`mx-auto w-full max-w-[86rem] px-5 sm:px-8 lg:px-12 ${className}`}>
      {children}
    </div>
  );
}

/**
 * The folio number and short title a scribe writes in the margin. The
 * numeral is generated by the page (`counter(leaf, devanagari)`), so leaves
 * always number themselves in reading order.
 */
function MarginMark({ label, inline = false }: { label?: string; inline?: boolean }) {
  return (
    <div
      aria-hidden="true"
      className={inline ? "mb-7 flex items-baseline gap-3" : "sticky top-8"}
    >
      <span
        data-leaf-no
        className={`block font-display leading-none text-cinnabar ${
          inline ? "text-[1.7rem]" : "text-[2.4rem]"
        }`}
      />
      {label ? (
        <span
          className={`block font-mono text-register text-ink-faint ${
            inline ? "" : "mt-3 max-w-[6rem]"
          }`}
        >
          {label}
        </span>
      ) : null}
    </div>
  );
}

/**
 * One leaf of the bundle — every section on the site. Three columns on wide
 * screens: the margin (folio number, short title), the ruled text block,
 * and an empty right margin that glosses float out into. The rule runs the
 * full height of the leaf, so stacked leaves draw one unbroken line.
 */
export function Leaf({
  id,
  label,
  children,
  className = "",
  innerClassName = "",
}: {
  id?: string;
  label?: string;
  children: ReactNode;
  className?: string;
  innerClassName?: string;
}) {
  return (
    <section id={id} data-leaf className={`scroll-mt-6 ${className}`}>
      <Container>
        <div className="grid md:grid-cols-[5.5rem_minmax(0,1fr)] lg:grid-cols-[7.5rem_minmax(0,1fr)_16rem]">
          <div className="hidden pt-[4.6rem] md:block lg:pt-[6.6rem]">
            <MarginMark label={label} />
          </div>
          <div
            className={`ruled min-w-0 py-14 pl-5 sm:pl-7 md:py-16 lg:py-24 lg:pl-12 ${innerClassName}`}
          >
            <div className="md:hidden">
              <MarginMark label={label} inline />
            </div>
            {children}
          </div>
          <div className="hidden lg:block" />
        </div>
      </Container>
    </section>
  );
}

/**
 * Section heading: incised, then inked as it scrolls into view, and closed
 * with a double danda in the scribe's red.
 */
export function Heading({
  children,
  as: Tag = "h2",
  className = "",
  size = "title",
}: {
  children: ReactNode;
  as?: "h1" | "h2" | "h3";
  className?: string;
  size?: "title" | "sub";
}) {
  const sizes = {
    title: "text-title",
    sub: "text-[clamp(1.55rem,1.2rem+1.1vw,2.1rem)] leading-[1.1]",
  } as const;
  return (
    <Tag
      className={`inked ink-on-scroll max-w-[24ch] text-balance font-display font-medium tracking-[-0.01em] ${sizes[size]} ${className}`}
    >
      {children}
      <span className="text-cinnabar" aria-hidden="true">
        {" "}॥
      </span>
    </Tag>
  );
}

export function Lede({ children, className = "" }: { children: ReactNode; className?: string }) {
  return (
    <p className={`mt-6 max-w-[56ch] text-lede text-ink ${className}`}>{children}</p>
  );
}

/** Running text at reading measure. */
export function Prose({ children, className = "" }: { children: ReactNode; className?: string }) {
  return (
    <div className={`mt-5 max-w-[60ch] space-y-5 text-[1.125rem] leading-[1.65] text-ink-soft ${className}`}>
      {children}
    </div>
  );
}

/**
 * A marginal gloss: the evidence beside the claim. Floats into the right
 * margin on wide screens; inline below that.
 */
export function Gloss({ label, children }: { label?: string; children: ReactNode }) {
  return (
    <aside className="gloss">
      {label ? <span className="block text-cinnabar">{label}</span> : null}
      <span className={label ? "mt-1 block" : "block"}>{children}</span>
    </aside>
  );
}

/**
 * A number the Foundation has not supplied yet.
 *
 * The site this replaces printed zeroes, and nothing ships until real counts
 * arrive — so an absent figure is drawn as a lacuna, a scribe's row of dots
 * over a gap in the text, and labelled. Never rendered as 0.
 */
export function Pending({
  width = "5rem",
  label,
}: {
  width?: string;
  label?: string;
}) {
  return (
    <span className="inline-flex flex-wrap items-center gap-x-3 gap-y-1">
      <span
        className="lacuna"
        style={{ width }}
        role="img"
        aria-label={label ? `Not yet published — ${label}` : "Not yet published"}
      />
      {label ? (
        <span className="font-mono text-register text-cinnabar" aria-hidden="true">
          {label}
        </span>
      ) : null}
    </span>
  );
}

/**
 * A variant reading, recorded in the margin rather than silently resolved:
 * where the Foundation's sources disagree, both are shown. The caret is the
 * kākapada, the mark a scribe uses to point at a marginal correction.
 */
export function EditorialNote({
  children,
  label = "Editorial note",
  className = "mt-8",
}: {
  children: ReactNode;
  label?: string;
  className?: string;
}) {
  return (
    <aside className={`max-w-[60ch] border-l border-cinnabar/50 pl-4 ${className}`}>
      <p className="font-mono text-register text-cinnabar">
        <span aria-hidden="true">‸ </span>
        {label}
      </p>
      <p className="mt-1 text-[0.98rem] leading-relaxed text-ink-soft">{children}</p>
    </aside>
  );
}

export function Button({
  href,
  children,
  variant = "primary",
}: {
  href: string;
  children: ReactNode;
  variant?: "primary" | "outline" | "outline-dark";
}) {
  const base =
    "inline-flex min-h-12 items-center justify-center px-6 py-3 text-[1.0625rem] leading-tight transition-colors duration-150";
  const styles = {
    primary: "bg-cinnabar text-leaf hover:bg-cinnabar-deep",
    outline: "border border-ink/40 text-ink hover:border-ink hover:bg-ink/[0.04]",
    "outline-dark": "border border-leaf/45 text-leaf hover:border-leaf hover:bg-leaf/10",
  } as const;
  return (
    <a href={href} className={`${base} ${styles[variant]}`}>
      {children}
    </a>
  );
}

/** An in-text link in the scribe's red. */
export function InlineLink({
  href,
  children,
  className = "mt-8",
}: {
  href: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <a
      href={href}
      className={`inline-block text-[1.0625rem] text-cinnabar underline decoration-cinnabar/35 decoration-1 underline-offset-[6px] transition-colors hover:decoration-cinnabar ${className}`}
    >
      {children}
    </a>
  );
}

/**
 * A register: figures set out as in a ledger — label, dotted leader, figure
 * — with the breakdown typed beneath. A `null` figure is a lacuna.
 */
export function Register({
  entries,
  className = "mt-10",
}: {
  entries: readonly { label: string; value: PendingValue<string>; note?: string }[];
  className?: string;
}) {
  return (
    <dl className={`max-w-[46rem] border-t border-ink/20 ${className}`}>
      {entries.map((entry) => (
        <div key={entry.label} className="border-b border-ink/20 py-4 sm:py-5">
          <div className="flex flex-wrap items-baseline gap-x-4 gap-y-1">
            <dt className="text-[1.125rem] text-ink">{entry.label}</dt>
            <span aria-hidden="true" className="leader hidden sm:block" />
            <dd className="ml-auto font-display text-[clamp(1.7rem,1.3rem+1.4vw,2.5rem)] font-medium leading-none tabular-nums text-ink">
              {entry.value ?? <Pending label="awaiting Foundation" width="6rem" />}
            </dd>
          </div>
          {entry.note ? (
            <dd className="mt-2 max-w-[52ch] font-mono text-register text-ink-faint">
              {entry.note}
            </dd>
          ) : null}
        </div>
      ))}
    </dl>
  );
}

/**
 * A numbered method, set as verses: each step closes with ॥n॥ in red, the
 * way a verse closes in a manuscript. Two columns on wide screens, read
 * down then across.
 */
export function Verses({
  steps,
  className = "mt-10",
}: {
  steps: readonly { title: string; body: string }[];
  className?: string;
}) {
  return (
    <ol data-verses className={`max-w-[60rem] gap-x-14 md:columns-2 ${className}`}>
      {steps.map((step) => (
        <li key={step.title} className="mb-7 break-inside-avoid border-t border-ink/15 pt-4">
          <h3 className="font-display text-[1.3rem] font-medium leading-snug text-ink">
            {step.title}
          </h3>
          <p data-verse-end className="mt-1.5 text-[1.0625rem] leading-relaxed text-ink-soft">
            {step.body}
          </p>
        </li>
      ))}
    </ol>
  );
}

type Person = { name: string; rank: string; body?: string; image: string };

/**
 * A wall of people: trustees, advisors, anyone the site introduces by
 * portrait. Photos stay full colour — the person is the point. What unifies
 * a grid of photos pulled from wildly different sources is the frame and
 * the interaction, not a filter over the image: see `PersonCard` for the
 * cursor-tilt.
 */
export function PersonGrid({
  people,
  columns = 3,
  className = "mt-12",
}: {
  people: readonly Person[];
  columns?: 3 | 4 | 5;
  className?: string;
}) {
  const cols = {
    3: "grid-cols-2 lg:grid-cols-3",
    4: "grid-cols-2 lg:grid-cols-4",
    5: "grid-cols-2 md:grid-cols-3 xl:grid-cols-5",
  }[columns];
  return (
    <ul className={`grid gap-x-6 gap-y-12 sm:gap-x-8 ${cols} ${className}`}>
      {people.map((person) => (
        <PersonCard key={person.name} person={person} />
      ))}
    </ul>
  );
}

/**
 * A photograph, tipped in: no mat and no drop shadow, a hairline edge, and
 * a catalogue caption numbered by the page ("Pl. ३").
 */
export function Plate({
  src,
  alt,
  caption,
  ratio = "4 / 3",
  className = "",
  imageClassName = "object-cover",
  sizes = "(min-width: 1024px) 40vw, 100vw",
  eager = false,
}: {
  src: string;
  alt: string;
  caption?: string;
  ratio?: string;
  className?: string;
  imageClassName?: string;
  sizes?: string;
  eager?: boolean;
}) {
  return (
    <figure data-plate className={className}>
      <div
        className="relative w-full overflow-hidden bg-leaf-deep outline outline-1 -outline-offset-1 outline-ink/15"
        style={{ aspectRatio: ratio }}
      >
        <Image
          src={src}
          alt={alt}
          fill
          sizes={sizes}
          loading={eager ? "eager" : "lazy"}
          fetchPriority={eager ? "high" : "auto"}
          className={imageClassName}
        />
      </div>
      {caption ? (
        <figcaption className="mt-3 max-w-[52ch] font-mono text-register text-ink-faint">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  );
}

/**
 * The first leaf of every page: title, lede, and — where the page has one —
 * a tall photograph that sits in the right margin and runs off the edge of
 * the screen. The home page's hero is a richer version of the same leaf.
 */
export function PageHero({
  label,
  eyebrow,
  title,
  body,
  plate,
  children,
}: {
  label?: string;
  eyebrow: string;
  title: string;
  body: string;
  plate?: { src: string; alt: string; caption?: string; position?: string };
  children?: ReactNode;
}) {
  return (
    <Leaf id="top" label={label ?? eyebrow} innerClassName="!pt-10 md:!pt-14 lg:!pt-20">
      <div className={plate ? "xl:grid xl:grid-cols-[minmax(0,1fr)_5rem] xl:gap-x-12" : ""}>
        <div className="min-w-0">
          <p className="font-mono text-register text-ink-faint">{eyebrow}</p>
          <h1 className="inked ink-on-load mt-5 max-w-[17ch] text-balance font-display text-display font-medium tracking-[-0.015em]">
            {title}
            <span className="text-cinnabar" aria-hidden="true">
              {" "}॥
            </span>
          </h1>
          <p className="mt-8 max-w-[52ch] text-lede text-ink">{body}</p>
          {children}
        </div>
        {plate ? <MarginPlate plate={plate} /> : null}
      </div>
    </Leaf>
  );
}

/**
 * A tall photograph that occupies the right margin of a title leaf and runs
 * off the edge of the screen — the one place a plate is allowed to break the
 * page's margins. Its grid track sits inside the text column; `bleed-right`
 * carries it out across the margin to the viewport.
 */
export function MarginPlate({
  plate,
}: {
  plate: { src: string; alt: string; caption?: string; position?: string };
}) {
  return (
    <figure data-plate className="bleed-right mt-12 flex flex-col xl:mt-0">
      <div className="relative aspect-[4/3] w-full overflow-hidden bg-leaf-deep sm:aspect-[16/9] xl:aspect-auto xl:min-h-[32rem] xl:flex-1">
        <Image
          src={plate.src}
          alt={plate.alt}
          fill
          loading="eager"
          fetchPriority="high"
          sizes="(min-width: 1280px) 30rem, 100vw"
          className="object-cover"
          style={{ objectPosition: plate.position ?? "center" }}
        />
      </div>
      {plate.caption ? (
        <figcaption className="mt-3 max-w-[38ch] pr-5 font-mono text-register text-ink-faint sm:pr-8">
          {plate.caption}
        </figcaption>
      ) : null}
    </figure>
  );
}
